### ISSUE TITLE
Represent indented blocks

### ISSUE THREAD

**Issue by AmjadHD** [BenjaminSchaaf/sbnf#17]
This is more of a support question, how to represent an indented block in sbnf.
I'm trying to implement a Nim syntax using it's [grammar spec](https://nim-lang.org/docs/manual.html#syntax-grammar) and sbnf but I'm stuck in expressing [indentation](https://nim-lang.org/docs/manual.html#lexical-analysis-indentation). How do I go about this ?

**Comment by BenjaminSchaaf** [comment]
I don't see a way of parsing indentation without a context-sensitive grammar - ie. it's not possible to express in SBNF.

**Comment by AmjadHD** [comment]
So I can't make a nim syntax (or python etc.) with sbnf ?

**Comment by BenjaminSchaaf** [comment]
You can't make one that understands indentation for Sublime Text in general. The Python syntax for instance ignores indentation.

**Comment by AmjadHD** [comment]
The point is I don't understand how to ignore indentation terminals and still use sbnf to make the syntax.

**Comment by BenjaminSchaaf** [comment]
Could you maybe provide an example of what you don't understand?
