### ISSUE TITLE
what type of parser is sublimetext?

### ISSUE THREAD

**Issue by arcturus140** [BenjaminSchaaf/sbnf#22]
what type of parser is ST, do i have to write my grammar for top-down or bottom-up?

**Comment by BenjaminSchaaf** [comment]
It's top-down: There's a stack of contexts where each context has a set of regex matches that can push or pop the stack. ST4 also adds backtracking. Pretty sure this doesn't matter for a BNF though?

**Comment by arcturus140** [comment]
It does for the parser, so I have to account for that in the grammar. The grammar doesn't care and can be written either way.
