### ISSUE TITLE
Regex equivalence branch points don't work in slightly different scenario

### ISSUE THREAD

**Issue by nuchi** [BenjaminSchaaf/sbnf#24]
The following (adapted from the unit tests in `src/compiler/mod.rs`, scopes changed to be visible in screenshots) works:
```sbnf
main = (a | b)*;
a{variable.function} = 'c'{ac} 'a';
b{variable.parameter} = 'c'{bc} 'b';
```
![image](https://user-images.githubusercontent.com/16771734/136117427-373ecc32-69df-4960-a37f-9b57bfa1c797.png)

But the following slight modification doesn't:
```sbnf
main = (`x` (a | b))*;
a{variable.function} = 'c'{ac} 'a';
b{variable.parameter} = 'c'{bc} 'b';
```
![image](https://user-images.githubusercontent.com/16771734/136117580-964b88f5-c8f4-418f-9ea6-7ca724075b34.png)

Interestingly, in the generated code, increasing the number of `pop`s after the `a` and `b` checks seems to fix this but I don't know why.
<details><summary>generated code</summary>

```diff
  %YAML 1.2
  ---
  # http://www.sublimetext.com/docs/syntax.html
  version: 2
  name: test
  file_extensions:
    - test
  scope: source.test
  contexts:
    a|0|main@1:
      - meta_include_prototype: false
      - match: 'c'
        scope: variable.function.test ac.test
        push: main|1|main@1
    b|0|main@1:
      - meta_include_prototype: false
      - match: 'c'
        scope: variable.parameter.test bc.test
        push: main|2|main@1
    # Include context for branch point main@1
    include!main@1:
      - match: '(?=c)'
        branch_point: main@1
        branch:
          - a|0|main@1
          - b|0|main@1
    # Rule: main
    main:
      - match: 'x'
        push: main|0
      - match: '\S'
        scope: invalid.illegal.test
    # Rule: main
    main|0:
      - include: include!main@1
      - match: '\S'
        scope: invalid.illegal.test
        pop: true
    # Rule: main
    #  For branch point 'main@1'
    main|1|main@1:
      - match: 'a'
        scope: variable.function.test
-       pop: true
+       pop: 3
      - match: '\S'
        fail: main@1
    # Rule: main
    #  For branch point 'main@1'
    main|2|main@1:
      - match: 'b'
        scope: variable.parameter.test
-       pop: true
+       pop: 3
      - match: '\S'
        scope: invalid.illegal.test
        pop: true
```
</details>

![image](https://user-images.githubusercontent.com/16771734/136118104-72a61c54-80a9-4822-b16c-36992cff8fe7.png)

Again, hoping that this is a misunderstanding on my part and would love to find a workaround if so!

**Comment by BenjaminSchaaf** [comment]
That's certainly a bug!

**Comment by nuchi** [comment]
I tried working through your code in order to understand how it works, and found it too difficult to wrap my head around, without understanding the underlying theory. So I went and learned a bit about parser construction.

And I, uh, went and started implementing my own syntax constructor. Thought you might be interested in taking a look. https://github.com/nuchi/sublime-from-cfg

**Comment by nuchi** [comment]
FYI for anyone reading along, I'm now self-hosting `sbnf.sbnf` and feature-complete. It's written in python. I haven't published to pypi yet but it's installable with `pip install 'sublime-from-cfg @ git+ssh://git@github.com/nuchi/sublime-from-cfg#egg=sublime-from-cfg'` and then `sublime-from-cfg /my/syntax/file.sbnf` once it's in your PATH.
