### ISSUE TITLE
Allow more unicode chars in rule names

### ISSUE THREAD

**Issue by eugenesvk** [BenjaminSchaaf/sbnf#33]
Currently clause/rule names have very limited syntax, thus preventing some more readable options in interpolations and in general combinations of various elements

For example, if I have a global regex var in Clauses
`NEWLINE = '(?>\r\n?|[\x{A}\x{C}\x{85}\x{2028}\x{2029}])'`
it would be great if I could use 
`␤ = '(?>\r\n?|[\x{A}\x{C}\x{85}\x{2028}\x{2029}])'`
instead, then that's easier to distinguish
`(x?: #[COMMENT_LINE] | #[newline]); `
`(x?: #[COMMENT_LINE] | #[␤]     ); `
`(x?: #[COMMENT_LINE] | #[NL]     ); ` and even shortened var name `NL` is less distinct as ␤ has no confusion with regular alpha chars

Or for `unicode-space:'[\x{9}\x{20}\x{A0}\x{1680}\x{2000}\x{2001}\x{2002}\x{2003}\x{2004}\x{2005}\x{2006}\x{2007}\x{2008}\x{2009}\x{200A}\x{202F}\x{205F}\x{3000}]';`

␠ could be a great indicator to signal that this is not a regular `sp` since it's using a unicode symbol

Or instead of some `left`/`right` word indicators I could use `←`/`→` — this is also much more readable

This would lead to a much nicer syntax definiton file

**Comment by BenjaminSchaaf** [comment]
"So" isn't a unicode category that should be used for identifiers, and generally isn't in other languages. It includes some blank characters among mostly symbols.

The current identifier syntax is not "very limited". It includes every alphabetic as well as the Nd Nl and No categories.

In general I'd also strongly recommend against using unicode characters for identifiers as they're difficult to work with. I'd personally avoid contributing to a syntax if it used characters I can't easily type.

**Comment by eugenesvk** [comment]
> "So" isn't a unicode category that should be used for identifiers. It includes some blank characters among mostly symbols.

The trivial solution to this issue is to exclude blank characters, not ban the whole category

>and generally isn't in other languages.

yeah, that's a very sad state of language design affairs

> The current identifier syntax is not "very limited". It includes 
> every alphabetic 

no, only latin alphabetic. Also, for variables that are usable in regexes, only CAPITAL letters

> as well as the Nd Nl and No categories.

so, that's a couple of dozen more numbers with permutations in various languages, most of which are not used anywhere, so useless for conveying info, and those that are used are not differentiated from, well, numbers?

How is not limited?

> In general I'd also strongly recommend against using unicode characters for identifiers as they're difficult to work with.

But this is not a general conversation about all languages, but specificly about a very niche one. And in the few instances where such extra symbols are allowed for the use case of configs of DSLs, it's been a delight of readability.

> I'd personally avoid contributing to a syntax if it used characters I can't easily type.

That's fine, these are not instances where much contribution is expected; as is typical for many such projects, it's mostly a work of a single person, so I would easily opt into the more ergonomic personal experience at the expense of hypothetical contributions

**Comment by BenjaminSchaaf** [comment]
> The trivial solution to this issue is to exclude blank characters, not ban the whole category

You can make this same argument for many more categories. There may be subsets of characters in most unicode categories that. I'm not about to trawl through all of unicode to find them, nor do I want to maintain the code and documentation for that.

> no, only latin alphabetic. Also, for variables that are usable in regexes, only CAPITAL letters

That is a bug. The intention in the parser it to support unicode but the codegen was validating only ascii identifiers. I've pushed a fix for that. I'd still generally recommend against using them as ST/yaml compatibility is not guaranteed. The capitalization requirement is intentional and won't be going away. I've currently not required unicode capitalization as I know languages aren't really consistent with that, but that may be added at a la

**Comment by eugenesvk** [comment]
> You can make this same argument for many more categories.

And it will continue to be the correct argument. It makes little sense to ban hundreds of symbols just because the category they're assigned to has a few that are bad

> There may be subsets of characters in most unicode categories that. I'm not about to trawl through all of unicode to find them,

And you don't need to, copy&paste from any language/syntax that has wide symbol support is a better alternative

> nor do I want to maintain the code and documentation for that.

But there is currently no documentation - for example, there is no doc that alt unicode numbers are supported. Extending the range doesn't **in itself** place any extra burden on that

> The capitalization requirement is intentional and won't be going away.

That's unfortunate, as that's another weird and very unergonomic limitation, e.g., I don't use caps lock, so it's actually harder to type ALL_CAPS than insert a `→` symbol

**Comment by BenjaminSchaaf** [comment]
> And you don't need to, copy&paste from any language/syntax that has wide symbol support is a better alternative

Well if it's that easy please feel free to submit a PR.

**Comment by eugenesvk** [comment]
> Well if it's that easy please feel free to submit a PR.

the easy part was referring to your claim that you need to wade through thousands of symbols, not re. how easy that would be to add to your code, and that's indeed easy, see the copy&paste of a list of symbols from an existing format below.

I might look into it, and since the whole thing was prompted by writing a KDL parser, and KDL has excellent unicode support in identifiers, I'd just copy their rules for unquoted (bare) identifiers:

https://github.com/kdl-org/kdl/blob/main/SPEC.md#non-identifier-characters
`identifier-char := unicode - linespace - [\/(){}<>;[]=,"]`
and `unicode` is everything above `0021`, and `linespace` excludes all the imaginable spacing characters (listed in the table in the linked spec)

Would that range work for you (despite your strong recommendations of not using these symbols, which can be reflected in the ReadMe)?

Could you then point to the code part that currently defines acceptable character ranges I could replace with the of the aforementioned codepoints?

**Comment by BenjaminSchaaf** [comment]
At a minimum it needs to exclude all ascii symbols, control characters, blank characters, non-printable, all characters that affect yaml in any way and probably something else I can't think of off the top of my head. It also needs to include the case rules and be performant without adding much bloat.

**Comment by eugenesvk** [comment]
> control characters
> non-printable
> all characters that affect yaml

Can just copy the yaml list https://yaml.org/spec/1.2.2/#character-set, it starts wit printables without controls, and excluding subsequent groups would cover ↑
(btw, per your fix above `ST/yaml compatibility is not guaranteed.`, so it's not really a minimum)

> , blank characters,

That's the various KDL whitespace

> it needs to exclude all ascii symbols

Shouldn't only those symbols that are used for SBNF syntax be excluded? Then the yaml list should cover these

>   It also needs to include the case rules

That's not a symbol list, and current implementation doesn't do that, so shouldn't be a requirement for extending the symbols

> I've currently not required unicode capitalization as I know languages aren't really consistent with that, 

> and be performant without adding much bloat

what's your performance test and budget?

**Comment by BenjaminSchaaf** [comment]
> Shouldn't only those symbols that are used for SBNF syntax be excluded? Then the yaml list should cover these

I don't want to further restrict the identifier syntax when new features are added to SBNF.

> what's your performance test and budget?

Checks for character types need to be sub-linear. There's no benchmarks yet, but if the code looks slow I'd like to see proof that it isn't. In terms of bloat approximately <50kB to the wasm binary.

**Comment by eugenesvk** [comment]
> There's no benchmarks yet, but if the code looks slow I'd like to see proof that it isn't.

But that's exactly what benchmarks are for, then I could simply remove a range at the top until it fits a performance/size budget

So I could do the part that is easy - copy&pasting a range of chars from existing syntaxes, and even the harder part of incorporating that into the parser (see the upcoming PR), but not matching non-existing test requirements

**Comment by mitranim** [comment]
I have no horse in this race, and for private use it's everyone's own business how they define their identifiers, but I do believe that limiting identifiers to ASCII alphanumerics is wise in any open source environment that may involve collaborators working on different operating systems, with different keyboard layouts, and so on. Special symbols tend to have names. By replacing those names with special symbols, you gain a little bit of brevity, but create friction by making things impossible to type and requiring copy-paste to do _anything_, and typically creating various edge case issues and breakages because some parts of the stack were not built to support that.

**Comment by mitranim** [comment]
Even if everyone had a magical keyboard layout that made it extra easy to produce special symbols (or we were all cyborgs with a BMI), special characters might _still_ not be worth it, due to visual ambiguities. Too many Unicode characters look alike.

**Comment by eugenesvk** [comment]
>  that may involve collaborators

This is mostly a nonexisting factor since for a lot of these projects there won't be collaborators, so it's not worth paying the price of ...

> you gain a little bit of brevity

- It's not a little (`r‹＃` vs `raw-hashed-quote-left`), and
- it's not just about brevity, it's about readability, symbols convey meaning faster/better than words 
(←→ vs left right) in a lot of cases

> special characters might still not be worth it, due to visual ambiguities. Too many Unicode characters look alike

- this issue already exists in since afaik not only latin scripts are supported.
- you don't have to use those bad chars just because the syntax supports them

>  and typically creating various edge case issues and breakages because some parts of the stack were not built to support that

An opportunity for the stack to move into the modern world (btw, which one is it in this case? syntax yaml supports unicode, so does Rust)

**Comment by eugenesvk** [comment]
> requiring copy-paste to do _anything_

we're not living in the ancient times of plain plain text editors, autocomplete is a thing

<img width="223" alt="scopeauto" src="https://github.com/BenjaminSchaaf/sbnf/assets/12956286/20f3dc75-66ad-4661-b31e-7a861bba8e92">
