### ISSUE TITLE
Using a rule with a terminal is not the same as using the same terminal

### ISSUE THREAD

**Issue by eugenesvk** [BenjaminSchaaf/sbnf#37]
I was hunting some syntax bug and was surprised to find out that simply including the same literal regex as a rule (see two `same-same` in the example below, one includes `=` literally, another includes a rule with the same terminal `eq:'=';`).
In this example concatenating `str` into a single regex also works
It seems that the only meaningful difference is the number of `pop`s (the fail rule has `2` while the regular rule pops only once)

This seriously hampers the ability to split larger regexes into smaller chunks and rather counterintuitive. Is there a way to make rules equivalent without having to collapse/inline literals?

```

main                          : (~test   )* ;##
test                          :'name' (same-same | argument)* ;
   argument                   :    (argval-as-key  | argval-not-key);
    argval-as-key {#[Z]}      :     keya   '(?!=)'     ; # MUST match 'key' to create a branching point due to regex equiv limit
    argval-not-key{#[Z]}      :     argval '(?!=)'     ;
   keya                       :(str|'b');
   argval                     :(str|'1');
   # same-same{  WORKS #[ZO]} :(str|'b')  '=' ('1') ;
   same-same{FAILS #[ZO]}     :(str|'b')  eq  ('1') ;
  eq                          : '=';
  str                         : '"' ~ '"';
  # str{Alternative Fix     } : '"[^"]*"';

Z  = 'punctuation.definition.string.DBG'
ZR = 'invalid.illegal.DBG'
ZB = 'entity.name.tag.DBG'
ZN = 'constant.numeric.DBG'
ZO = 'entity.other.attribute-name.DBG'
```

Testing text (everything should be highlighted, yet with a `FAILS` rule it stops after `b=1`)
```
name 1 1 b=1 1 "a"=1 1 "a" b=1;
name b=1 1 "a"=1;
name b=1 1 "a"=1;
```

**Comment by eugenesvk** [comment]
Not sure if this is similar, but another weird difference in conceptually identical rules depending on where you add `*` to the same rule - within the rule itself or within an invocation of a rule

1. this working rule that matches repeated `1`s in `a 1 1`;
```
main   : 'a' (repeat1)*  '#[MAYBE_END]';
repeat1: ('1' '(?=#[MAYBE_END])'?);
MAYBE_END=';|\n'
```
is different than
2. this failing rule that matches only the first `1` with an asterisks placed conceptually at the same place (repeat everything in rule `repeat1`, but only this time within the `repeat1` rule itself
```
main   : 'a' (repeat1)  '#[MAYBE_END]';
repeat1: ('1' '(?=#[MAYBE_END])'?)*;
MAYBE_END=';|\n'
```

**Comment by BenjaminSchaaf** [comment]
This is the same bug as #39
