### ISSUE TITLE
Apply scope to the end of existing rules

### ISSUE THREAD

**Issue by eugenesvk** [BenjaminSchaaf/sbnf#42]
I'd like to append some scope to existing rules to e.g. signify that a given parsed data element is part of a special valid block comment

If I do the following with a special `comment-rule`, then the scope `meta-scope-comment-rule` is PREpended, so requires special handling in a color scheme.
```
comment-rule{meta-scope-comment-rule}	: rule                                   	;
rule{        meta-scope-rule}        	: 'terminal-regex'{scope-higher-priority}	;
```

Instead I'd like to do append scope to all the elements of a given rule so that that scope beats all the others
`comment-rule	: rule{scope-appended-highest-priority}	;`

**Comment by BenjaminSchaaf** [comment]
Duplicate of #14
