### ISSUE TITLE
Version 0.6.0 binary for MacOS reports version 0.5.1

### ISSUE THREAD

**Issue by jhermsmeier** [BenjaminSchaaf/sbnf#44]
The `sbnf-compiler-x86_64-apple-darwin-0.6.0.tar.xz` binary from [sbnf/releases/tag/0.6.0](https://github.com/BenjaminSchaaf/sbnf/releases/tag/0.6.0) reports version 0.5.1

```console
> sbnf --version
SBNF compiler 0.5.1
```

**Comment by BenjaminSchaaf** [comment]
Fixed with 0.6.1
