### ISSUE TITLE
Release 0.6.3 detects syntax error in sbnf.sbnf on Windows

### ISSUE THREAD

**Issue by deathaxe** [BenjaminSchaaf/sbnf#45]
Is the following parse error expected?

![grafik](https://github.com/BenjaminSchaaf/sbnf/assets/16542113/ee7e2dff-3838-4545-95ca-8af022ace84f)

Just tried to compile sbnf.sbnf using sbnf package 0.6.3

**Comment by BenjaminSchaaf** [comment]
Looks like you're using windows newlines? That probably shouldn't break parsing though.

**Comment by deathaxe** [comment]
Just installed the package using Package Control, opened sbnf.sbnf and hit ctrl+b.

EDIT: Well, git globally translates linefeeds of cloned repos on Windows by default.

EDIT2: Explicitly setting unix style line endings, fixes it. IMHO should work with windows line feeds as well on windows.

**Comment by BenjaminSchaaf** [comment]
Fixed by 54273179186cc6475b66b16cc6e0fce3d66050e1
