### ISSUE TITLE
Meta: Sublime syntax for BNF/SBNF?

### ISSUE THREAD

**Issue by mitranim** [BenjaminSchaaf/sbnf#8]
Brief search didn't turn up any results. It would be quite fitting for the syntax to describe itself, and make it easier to use the notation.

The obvious response is "contributions are welcome, do it yourself". 🙂 Might eventually. Just leaving it here as an idea.

**Comment by BenjaminSchaaf** [comment]
It's right here: https://github.com/BenjaminSchaaf/sbnf/blob/master/sbnf/sbnf.sbnf You just need to compile it yourself :)

**Comment by mitranim** [comment]
Good to know! Perhaps the readme should mention it.

**Comment by BenjaminSchaaf** [comment]
Good suggestion, I've pushed a fix for that.
